name: Docker image build and push

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.2

    - name: Get latest release
      run: |
        export RELEASE_LATEST=$(curl -s "https://api.github.com/repos/Koenkk/zigbee2mqtt/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
        echo "::set-env name=VERSION::$RELEASE_LATEST"
      shell: bash
    
    - name: Always build the latest Docker image
      run: docker build --build-arg VERSION=master -t zigbee2mqtt:latest .

    - name: Compare release with already pushed version
      run: |
        export RELEASE_AVAIL=$(curl -s "https://hub.docker.com/v2/repositories/urfin78/zigbee2mqtt-i386/tags/"|grep -Po "$VERSION")
        echo "::set-env name=AVAIL::$RELEASE_AVAIL"
      if: success()

    - name: Build the Docker image for new version
      run: docker build --build-arg VERSION=$VERSION -t zigbee2mqtt:$VERSION .
      if: success() && env.VERSION != env.AVAIL
    
    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin

    - name: Tag the latest Docker image
      run: docker tag zigbee2mqtt:latest docker.pkg.github.com/urfin78/zigbee2mqtt-docker-i386/zigbee2mqtt:latest
      if: success()

    - name: Push the latest image to GPR
      run: docker push docker.pkg.github.com/urfin78/zigbee2mqtt-docker-i386/zigbee2mqtt:latest
      if: success()

    - name: Tag the new version Docker image
      run: docker tag zigbee2mqtt:$VERSION docker.pkg.github.com/urfin78/zigbee2mqtt-docker-i386/zigbee2mqtt:$VERSION
      if: success() && env.VERSION != env.AVAIL

    - name: Push the new version image to GPR
      run: docker push docker.pkg.github.com/urfin78/zigbee2mqtt-docker-i386/zigbee2mqtt:$VERSION
      if: success() && env.VERSION != env.AVAIL

    - name: Logout from GitHub Registry
      run: docker logout docker.pkg.github.com

    - name: Login to Dockerhub Registry
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      if: success()
    
    - name: Tag the latest Docker image
      run: docker tag zigbee2mqtt:latest urfin78/zigbee2mqtt-i386:latest
      if: success()
   
    - name: Push the latest image to Dockerhub
      run: docker push urfin78/zigbee2mqtt-i386:latest
      if: success()
      
    - name: Tag the new version Docker image
      run: docker tag zigbee2mqtt:$VERSION urfin78/zigbee2mqtt-i386:$VERSION
      if: success() && env.VERSION != env.AVAIL
   
    - name: Push the new version image to Dockerhub
      run: docker push urfin78/zigbee2mqtt-i386:$VERSION
      if: success() && env.VERSION != env.AVAIL
    
    - name: Logout from Dockerhub Registry
      run: docker logout
